#!/bin/bash
################################################################################
#
# Copyright (c) 2019 NUAA AeroLab
#
# @author   Jiang Yang (pokerpoke@qq.com)
# @date     2018-08
# @brief
# @version  0.0.1
#
# Last Modified:  2019-05-21
# Modified By:    Jiang Yang (pokerpoke@qq.com)
#
################################################################################
set -e

# get scripts directory
CMAKE_SOURCE_DIR=$(dirname $(readlink -f $0))
# update cmake source path
CMAKE_SOURCE_DIR=$(pwd)
cd ${CMAKE_SOURCE_DIR}

if [ ! -d ./cmake-build-debug ]
then
   mkdir cmake-build-debug
fi

if [ "$2" = "all" ]
then
  echo "clean all"
  cd cmake-build-debug && cmake .. && make clean && cmake ..  && make -j8 && cd src
else
  if [ ! f cmake-build-debug/src/$1 ]
  then
    echo "not clean all"
    cd cmake-build-debug && cmake .. && make $1 -j8 && cd src
  else
    cd cmake-build-debug && cmake .. && make $1 -j8 && cd src
  fi
fi

./$1